# Generated by Django 4.2.16 on 2024-11-05 06:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("flights", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="flight",
            table="flights_flight",
        ),
    ]
