# Generated by Django 4.2.16 on 2024-11-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flight_number", models.CharField(max_length=10)),
                ("departure_city", models.CharField(max_length=100)),
                ("arrival_city", models.CharField(max_length=100)),
                ("departure_date", models.DateField()),
                ("departure_time", models.TimeField()),
                ("arrival_time", models.TimeField()),
                ("duration", models.CharField(max_length=100)),
                ("aircraft", models.CharField(max_length=100)),
                ("price_economy", models.DecimalField(decimal_places=2, max_digits=8)),
                ("price_premium", models.DecimalField(decimal_places=2, max_digits=8)),
                ("price_first", models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
