# Generated by Django 5.1.3 on 2024-11-07 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserPage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='postal_code',
            new_name='postalCode',
        ),
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.TextField(),
        ),
    ]
