# Generated by Django 5.1.3 on 2024-11-07 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserPage', '0002_rename_first_name_user_firstname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='user',
        ),
    ]
